/*pub mod array;
pub mod bulk_string;
pub(crate) mod error;
pub(crate) mod integer;
pub(crate) mod redis_type;
pub mod simple_string;*/
pub mod array;
pub mod bulk_string;
pub mod error;
pub mod integer;
pub mod redis_type;
pub mod simple_string;

pub use array::RArray;
pub use bulk_string::RBulkString;
pub use error::ErrorStruct;
pub use error::RError;
pub use integer::RInteger;
pub use redis_type::RedisType;
pub use simple_string::RSimpleString;
